### ISSUE TITLE
Unable to fetch transactions on Android SDK

### ISSUE THREAD

**Issue by Zfinix** [mirrorworld-universe/mirrorworld-sdk-android#22]
I am unable to get transactions on the SDK:

```kotlin   
        private fun getTransactions(call: MethodCall) {
        val limit = call.argument<Int>("limit") ?: 0
        val before = call.argument<String>("before") ?: ""

        MirrorWorld.getTransactions(
            limit, before,
            object : GetWalletTransactionListener {
                override fun onSuccess(res: GetWalletTransactionsResponse) {
                    events?.success(
                        EventsHelper.mapEvent(
                            name = EventsHelper.getTransactions,
                            data = EventsHelper.toMap(res)
                        )
                    )
                }

                override fun onFailed(code: Long, message: String) {
                    onFetchFailed(code, message)
                }
            },
        )
    }
 ```
Each time i run this function my app crashes with this error?
```
W/System.err: java.io.FileNotFoundException: https://api.mirrorworld.fun/v1/devnet/wallet/transactions?before=bvcofigBLTmy3DJ29P8Nfh5aJ1GHwS6ncSmTBZdYGfXCs2e5pvY7nV8zBXYefoeczggVXEkKAkNy1GAZPpHhmWi
W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:255)
W/System.err:     at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
W/System.err:     at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
W/System.err:     at com.mirror.sdk.MirrorSDK.httpGetW(MirrorSDK.java:2007)
W/System.err:     at com.mirror.sdk.MirrorSDK.-$$Nest$mhttpGetW(Unknown Source:0)
W/System.err:     at com.mirror.sdk.MirrorSDK$47.run(MirrorSDK.java:1746)
W/System.err:     at java.lang.Thread.run(Thread.java:923)
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mirrorworld.universe.example, PID: 17355
    java.lang.NullPointerException: Attempt to read from field 'long com.mirror.sdk.response.CommonResponse.code' on a null object reference
        at com.mirror.sdk.MirrorSDK$31.callback(MirrorSDK.java:1208)
        at com.mirror.sdk.MirrorSDK$47$1.run(MirrorSDK.java:1754)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
I/Process: Sending signal. PID: 17355 SIG: 9
```

**Comment by codebender828** [comment]
Thanks @Zfinix For capturing this. @SuQiang2007 could you take a look into this?

**Comment by SuQiang2007** [comment]
Thanks for the feedback.
We have identified the issue and fixing it. When it is done, I will give another comment here.
Thanks for your waiting.
